# Generated by Django 4.1.6 on 2023-03-15 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leagues',
            name='league_id',
        ),
    ]
